// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyjvccprspgsmpwozqmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5anZjY3Byc3Bnc21wd296cW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDMyOTEsImV4cCI6MjA2ODE3OTI5MX0.B4YS4sb8178XuQ5c-nCbeNZ0Vz5dyawkIEZslRdKmmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});